name: Create SDKs

on: push

permissions:
  contents: write

jobs:
  create:
    runs-on: macos-latest

    steps:
      - name: Clone tools
        uses: actions/checkout@v4
        with:
          sparse-checkout: "tools/"

      - name: Install blacktop/ipsw
        run: brew install blacktop/tap/ipsw

      - name: Patch SDK
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # config
          XC_SDK_NAME="appletvos"
          SDK_PREFIX="AppleTVOS"
          IPSW_DEVICE="AppleTV5,3"
          DSC_BASENAME="dyld_shared_cache_arm64"

          cd tools/
          PLATFORM_PATH="$(xcrun --sdk "${XC_SDK_NAME}" --show-sdk-platform-path)"
          BASE_SDK_PATH="$(xcrun --sdk "${XC_SDK_NAME}" --show-sdk-path)"

          SDK_VERSION="$(plutil -extract "Version" raw -o - "${BASE_SDK_PATH}/SDKSettings.plist")"
          SDK_OUTPUT_PATH="${SDK_PREFIX}${SDK_VERSION}.sdk"

          SYMBOLS_DIR="$(mktemp -d -t symbols)"
          DSC_DOWNLOAD_DIR="$(mktemp -d -t dsc)"
          TBD_TOOL_PATH="$(mktemp -t tbd)"

          curl -L "https://github.com/inoahdev/tbd/releases/download/2.2/tbd-mac" -o "${TBD_TOOL_PATH}"
          chmod 0755 "${TBD_TOOL_PATH}"

          # iPhone14,6 random device that support iOS 15+
          ipsw download ipsw --dyld --output "${DSC_DOWNLOAD_DIR}" --version "${SDK_VERSION}" --device "${IPSW_DEVICE}"

          DYLD_CACHE_PATH="$(echo "${DSC_DOWNLOAD_DIR}"/*/"${DSC_BASENAME}")"
          echo "DYLD_CACHE_PATH = ${DYLD_CACHE_PATH}"

          make dsc_extractor_client
          ./dsc_extractor_client "${PLATFORM_PATH}/usr/lib/dsc_extractor.bundle" "${DYLD_CACHE_PATH}" "${SYMBOLS_DIR}"
          ./create_patched_sdk.sh "${SYMBOLS_DIR}" "${SDK_OUTPUT_PATH}" "${BASE_SDK_PATH}" "${TBD_TOOL_PATH}"

          tar -cJf "${SDK_OUTPUT_PATH}.tar.xz" "${SDK_OUTPUT_PATH}"

          RELEASE_TAG="auto-${GITHUB_SHA:0:7}"
          gh release create "${RELEASE_TAG}" --draft --title "Draft Release"
          gh release upload "${RELEASE_TAG}" "${SDK_OUTPUT_PATH}.tar.xz"
