name: Create SDKs

on: push

jobs:
  create:
    # https://github.com/actions/runner-images/blob/main/images/macos
    runs-on: macos-14
    # needed to be able to create a Release
    permissions:
      contents: write

    env:
      XCODE_VERSION: "14.3.1"
      # iOS config
      IPSW_DEVICE: "iPhone11,2" # supports iOS 12+
      IPSW_VERSION: "16.4"
      XC_SDK_NAME: "iphoneos"
      SDK_PREFIX: "iPhoneOS"
      DSC_BASENAME: "dyld_shared_cache_arm64e"

      # tvOS config
      # IPSW_DEVICE: "AppleTV5,3"
      # IPSW_VERSION: "17.1"
      # XC_SDK_NAME: "appletvos"
      # SDK_PREFIX: "AppleTVOS"
      # DSC_BASENAME: "dyld_shared_cache_arm64"

    steps:
      - name: Clone tools
        uses: actions/checkout@v4
        with:
          sparse-checkout: "tools/"

      - name: Clone tbd
        uses: actions/checkout@v4
        with:
          repository: leptos-null/tbd
          ref: f0ae164d76b7bb802bbdf8ef758cc5637fac0fa1 # pinned, leptos/source-platform
          path: tbd

      - name: Build tbd
        run: |
          cd tbd
          make bin/tbd

      - name: Create cache key
        id: cache-key
        run: |
          # replace ',' with '_', since ',' is not allowed in cache keys
          echo "device-component=${IPSW_DEVICE//,/_}" >> "$GITHUB_OUTPUT"

      - name: IPSW cache
        id: ipsw-cache
        uses: actions/cache@v4
        with:
          path: ipsws/os.ipsw
          key: ipsw-${{ steps.cache-key.outputs.device-component }}-${{ env.IPSW_VERSION }}

      - name: Install blacktop/ipsw
        if: steps.ipsw-cache.outputs.cache-hit != 'true'
        run: brew install blacktop/tap/ipsw

      - name: Install aria2
        if: steps.ipsw-cache.outputs.cache-hit != 'true'
        run: brew install aria2

      - name: Download IPSW
        if: steps.ipsw-cache.outputs.cache-hit != 'true'
        run: |
          # `--dyld` is a convenient parameter for us, however it only supports iOS 16+
          IPSW_DOWNLOAD_URL="$(ipsw download ipsw --urls --version "${IPSW_VERSION}" --device "${IPSW_DEVICE}")"
          echo "Downloading ${IPSW_DOWNLOAD_URL}"
          IPSW_DOWNLOAD_DIR="$(mktemp -d -t ipsw)"
          aria2c --dir "${IPSW_DOWNLOAD_DIR}" "${IPSW_DOWNLOAD_URL}"

          mkdir ipsws
          mv "${IPSW_DOWNLOAD_DIR}"/*.ipsw "ipsws/os.ipsw" # cache path

      - name: Patch SDK
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ env.XCODE_VERSION }}.app
          GH_TOKEN: ${{ github.token }}
        run: |
          # use absolute path since we `cd` later
          TBD_TOOL_PATH="$(pwd)/tbd/bin/tbd"

          cd tools/
          PLATFORM_PATH="$(xcrun --sdk "${XC_SDK_NAME}" --show-sdk-platform-path)"
          BASE_SDK_PATH="$(xcrun --sdk "${XC_SDK_NAME}" --show-sdk-path)"

          SDK_VERSION="${IPSW_VERSION}"
          SDK_OUTPUT_PATH="${SDK_PREFIX}${SDK_VERSION}.sdk"

          SYMBOLS_DIR="$(mktemp -d -t symbols)"
          IPSW_EXTRACTION_DIR="$(mktemp -d -t ipsw)"

          unzip -d "${IPSW_EXTRACTION_DIR}" "../ipsws/os.ipsw" "*.dmg"

          for DMG_FILE in "${IPSW_EXTRACTION_DIR}"/*.dmg; do
            # new mount root for each dmg so we don't have to
            # worry about how we iterate over the mount root
            DMG_MOUNT_ROOT="$(mktemp -d -t dmg)"
            # some of the dmgs can't be mounted - not sure why
            hdiutil attach "${DMG_FILE}" -mountroot "${DMG_MOUNT_ROOT}" || true
            for MOUNT_VOL in "${DMG_MOUNT_ROOT}"/*; do
              DYLD_CACHE_PATH="${MOUNT_VOL}/System/Library/Caches/com.apple.dyld/${DSC_BASENAME}"
              if [[ -e "${DYLD_CACHE_PATH}" ]]; then
                break 2 # break out of DMG_FILE loop
              fi
              # here becuase we didn't find the dyld shared cache (didn't break)
              unset DYLD_CACHE_PATH
              hdiutil detach "${MOUNT_VOL}" || true # this fails occasionally - just ignore
            done
          done

          echo "Found dyld_shared_cache: ${DYLD_CACHE_PATH}"

          if [[ -z "${DYLD_CACHE_PATH}" ]]; then
            echo "Failed to find ${DSC_BASENAME} in IPSW"
            exit 1
          fi

          make dsc_extractor_client
          ./dsc_extractor_client "${PLATFORM_PATH}/usr/lib/dsc_extractor.bundle" "${DYLD_CACHE_PATH}" "${SYMBOLS_DIR}"
          ./create_patched_sdk.sh "${SYMBOLS_DIR}" "${SDK_OUTPUT_PATH}" "${BASE_SDK_PATH}" "${TBD_TOOL_PATH}"

          tar -cJf "${SDK_OUTPUT_PATH}.tar.xz" "${SDK_OUTPUT_PATH}"

          RELEASE_TAG="auto-${GITHUB_SHA:0:7}"
          gh release create "${RELEASE_TAG}" --draft \
            --title "Draft ${SDK_PREFIX}${SDK_VERSION}.sdk" \
            "${SDK_OUTPUT_PATH}.tar.xz"
